version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3313:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  singleton:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_TYPE=mysql
    working_dir: /app
    volumes:
      - .:/app     # Mount the current directory to /app in the container
      - /app/tmp    # Optional: Separate tmp folder to prevent caching issues
    ports:
      - "8081:8080"
    command: air    # Start the app with Air for live reloading
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
